[package]
name = "malus"
version = "0.0.0"
authors = ["Jamie Quigley <jamie@quigley.xyz>"]
edition = "2021"
license = "MPL-2.0"
description = "macOS status monitoring - WIP"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
